const JOBS = {
  LOAD: "JOBS_LOAD",
  LOAD_SUCCESS: "JOBS_LOAD_SUCCESS",
  LOAD_FAILURE: "JOBS_LOAD_FAILURE"
};

const DETAILS = {
  LOAD: "DETAILS_LOAD",
  LOAD_SUCCESS: "DETAILS_LOAD_SUCCESS",
  LOAD_FAILURE: "DETAILS_LOAD_FAILURE"
};

export { JOBS, DETAILS };
